### ISSUE TITLE
Issue with categorical rasterstats

### ISSUE THREAD

**Issue by marsmith** [perrygeo/python-rasterstats#115]
Following the tutorial here to get raster stats I'm getting a python error:
http://blog.perrygeo.net/2013/09/24/python-raster-stats/

runStats.py:
```
import sys
from rasterstats import zonal_stats

#run zonal stats
stats = zonal_stats(sys.argv[1], sys.argv[2], categorical=True)
print stats
```

error:
```
osboxes@osboxes:~/node-zonalstats$ python runStats.py "input/GlobalWatershed.shp" "../data/nlcd_2011_landcover_2011_edition_2014_10_10.img"
/usr/local/lib/python2.7/dist-packages/rasterstats/io.py:281: UserWarning: Setting nodata to -999; specify nodata explicitly
  warnings.warn("Setting nodata to -999; specify nodata explicitly")
Traceback (most recent call last):
  File "runStats.py", line 5, in <module>
    stats = zonal_stats(sys.argv[1], sys.argv[2], categorical=True)
  File "/usr/local/lib/python2.7/dist-packages/rasterstats/main.py", line 21, in zonal_stats
    return list(gen_zonal_stats(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/rasterstats/main.py", line 157, in gen_zonal_stats
    keys, counts = np.unique(masked.compressed(), return_counts=True)
TypeError: unique() got an unexpected keyword argument 'return_counts'
osboxes@osboxes:~/node-zonalstats$ 
```

if I remove the "categorical=true" argument from runStats.py I get stats so I'm pretty sure my input and raster are fine:
```
[{'count': 2284, 'max': 95.0, 'mean': 57.90323992994746, 'min': 21.0}]
```

Running clean install of rasterstats on ubuntu 14.04
any ideas on this?  Seems like I'm using pretty out of the box functionality here? Thanks!

**Comment by marsmith** [comment]
Resolved this.  Turns out my numpy version was <1.9 which is a requirement for this "return_count" argument in np.unique().  fixed with force upgrade of numpy 

```
sudo pip install numpy --upgrade
```

**Comment by perrygeo** [comment]
Recent versions of rasterstats have a hard requirement for `numpy>=1.9` so it will be more clear at install time.
