### ISSUE TITLE
File "rasterio/_io.pyx", line 810, in rasterio._io.RasterReader.read (rasterio/_io.c:10370) MemoryError

### ISSUE THREAD

**Issue by tonussi** [perrygeo/python-rasterstats#160]
# LINKS

+ https://www.dropbox.com/s/k8gjju0vnu45bxi/MCD13Q1_2000049_EVI2.tif?dl=0
+ https://www.dropbox.com/s/317ydjwtsc6bdz3/poligono.dbf?dl=0
+ https://www.dropbox.com/s/z591awjpruy7q4i/poligono.prj?dl=0
+ https://www.dropbox.com/s/o6wj73u9bue81ps/poligono.shp?dl=0
+ https://www.dropbox.com/s/ypgmrg627k2e8te/poligono.shx?dl=0

# INPUT

``` python
from rasterstats import zonal_stats

input_zone_polygon = "data/poligono.shp"
input_value_raster = "data/MCD13Q1_2000049_EVI2.tif"

stats = zonal_stats(input_zone_polygon, input_value_raster)
print(stats[1].keys())
print([f['mean'] for f in stats])
```

# OUTPUT

``` python
Ran 1 test in 0.012s

FAILED (errors=1)

Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/<user>/PycharmProjects/geoprocessing/tests/test_ams_zonalstats.py", line 96, in test_get_stats
    stats = zonal_stats(input_zone_polygon, input_value_raster)
  File "/home/<user>/Envs/geopross/local/lib/python2.7/site-packages/rasterstats/main.py", line 31, in zonal_stats
    return list(gen_zonal_stats(*args, **kwargs))
  File "/home/<user>/Envs/geopross/local/lib/python2.7/site-packages/rasterstats/main.py", line 155, in gen_zonal_stats
    fsrc = rast.read(bounds=geom_bounds)
  File "/home/<user>/Envs/geopross/local/lib/python2.7/site-packages/rasterstats/io.py", line 303, in read
    self.band, window=win, boundless=True, masked=masked)
  File "rasterio/_io.pyx", line 810, in rasterio._io.RasterReader.read (rasterio/_io.c:10370)
MemoryError

Process finished with exit code 1
```

# POSSIBLE SOLUTION

https://pcjericks.github.io/py-gdalogr-cookbook/raster_layers.html#calculate-zonal-statistics

**Comment by perrygeo** [comment]
As the traceback indicates,  rasterio was unable to read the data into memory. Rasterstats has been made as memory efficient as possible, only loading the raster data necessary for determining the zonal statistics for each feature. If you're hitting Memory errors, you'll either need to use a system with more free memory or a downsampled version of the raster.
