### ISSUE TITLE
cannot reproduce muliprocessing

### ISSUE THREAD

**Issue by GloryPassarello** [perrygeo/python-rasterstats#179]
I am studying how to runs the zonal statistics function on a multiprocessing. [This ](https://github.com/perrygeo/python-rasterstats/blob/master/examples/multiproc.py) is a great code (Many thanks ^_^) !!

Unfortunately I am not able to run the code.  
I got back this error: 
`rasterio.errors.CRSError: CRS is empty or invalid: ''`

I am not sure if the issue could be on the part: 

```
with fiona.open(shp) as src:
        features = list(src)
```

on features I have back a list of dictionaries and the `zonal_stats` function is not working... should the vector argument of zonal_stats be  a `'fiona.collection.Collection'` and not a dictionary to work?

I can reproduce the error also if I run: 

```
shp = fiona.open(vector_file)
for x in features:
    zonal_stats(vectors=x, raster= raster_file, stats=['sum'])
```

Many thanks!!

**Comment by perrygeo** [comment]
Can you reproduce this with your final code snippet against some of the test data? https://github.com/perrygeo/python-rasterstats/tree/master/tests/data

Otherwise, can you provide links to download the smallest dataset needed to reproduce the error? Thanks.

**Comment by GloryPassarello** [comment]
Dear @perrygeo Many thanks for your fast reply. Running the test data, I gave back [this issues](https://github.com/mapbox/rasterio/issues/1539) and solving this the code with them goes like a charm. I also used my Tiff file with a shape file I created and also runs great! 
I also tried with a subset of my working data and it goes correctly. 

when I try to run it on my entire data I have bask this: 


```
ERROR 1: TIFFFetchStripThing:IO error during reading of "StripOffsets"
ERROR 1: TIFFFillStrip:Read error at scanline 13816; got 979 bytes, expected 1024
ERROR 1: TIFFReadEncodedStrip() failed.
ERROR 1: /media/sf_ESPON_DATA/subset/medium_output/esm_clc_r.tif, band 1: IReadBlock failed at X offset 0, Y offset 13817: TIFFReadEncodedStrip() failed.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "zonal_stat_parallel_2.py", line 34, in zonal_stats_partial
    return zonal_stats(feats, tif, stats=['sum'])
  File "/usr/local/lib/python3.6/dist-packages/rasterstats/main.py", line 31, in zonal_stats
    return list(gen_zonal_stats(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/rasterstats/main.py", line 155, in gen_zonal_stats
    fsrc = rast.read(bounds=geom_bounds)
  File "/usr/local/lib/python3.6/dist-packages/rasterstats/io.py", line 303, in read
    self.band, window=win, boundless=True, masked=masked)
  File "rasterio/_io.pyx", line 394, in rasterio._io.DatasetReaderBase.read
  File "rasterio/_io.pyx", line 396, in rasterio._io.DatasetReaderBase.read
  File "rasterio/_io.pyx", line 716, in rasterio._io.DatasetReaderBase._read
OSError: Read or write failed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "zonal_stat_parallel_2.py", line 48, in <module>
    stats_lists = p.map(zonal_stats_partial, chunks(features, cores))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
OSError: Read or write failed

```

**Comment by perrygeo** [comment]
The first 4 lines with `ERROR 1` indicate clearly that the problem is with your tif file.
